server:
    servlet:
      context-path: /product

spring:
  datasource:
    druid:
      # 数据库访问配置, 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8
      username: root
      password: root
      # 连接池配置
      initial-size: 2
      min-idle: 1
      max-active: 3
      # 连接等待超时时间
      max-wait: 10000

#pagehelper
pagehelper:
  helperDialect: oracle
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

logging:
  level:
    com:
      springboot:
        mapper: debug

mybatis:
  mapper-locations: classpath:mapper/*.xml